# Generated by Django 6.0.4 on 2026-05-31 17:55

import django.core.validators
import django.db.models.deletion
import workouts.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whoop', 'Whoop'), ('oura', 'Oura Ring'), ('polar', 'Polar'), ('garmin', 'Garmin'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('strava', 'Strava'), ('wahoo', 'Wahoo'), ('suunto', 'Suunto'), ('coros', 'Coros'), ('ultrahuman', 'Ultrahuman'), ('myfitnesspal', 'MyFitnessPal'), ('eight_sleep', 'Eight Sleep'), ('manual', 'Manual Entry')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', workouts.crypto.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', workouts.crypto.EncryptedTextField(blank=True, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('provider_user_id', models.CharField(blank=True, help_text='User ID in provider system (e.g. Garmin Connect ID, Polar Flow ID)', max_length=255, null=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='OAuth scopes granted for this user while connecting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source_label', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('sleep_duration', models.DurationField(blank=True, null=True)),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recovery_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hrv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rhr', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(120)])),
                ('deep_sleep', models.DurationField(blank=True, null=True)),
                ('rem_sleep', models.DurationField(blank=True, null=True)),
                ('light_sleep', models.DurationField(blank=True, null=True)),
                ('awake_time', models.DurationField(blank=True, null=True)),
                ('sleep_consistency', models.PositiveSmallIntegerField(blank=True, help_text='Sleep consistency 1-100% (Whoop Consistency, Oura Regularity, etc.)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=1, help_text='Respiratory rate in breaths per minute', max_digits=4, null=True)),
                ('skin_temp_delta', models.DecimalField(blank=True, decimal_places=1, help_text='Skin temperature delta vs baseline', max_digits=4, null=True)),
                ('spo2_avg', models.DecimalField(blank=True, decimal_places=1, help_text='Average blood oxygen (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(70.0), django.core.validators.MaxValueValidator(100.0)])),
                ('spo2_min', models.DecimalField(blank=True, decimal_places=1, help_text='Min SpO2 at night', max_digits=4, null=True)),
                ('vo2max', models.DecimalField(blank=True, decimal_places=1, help_text='VO2max (ml/kg/min) — Garmin/Polar estimate', max_digits=4, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.datasource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility/Mobility'), ('specific', 'Sport Specific/Other')], max_length=50)),
                ('external_mapping', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='workouts.sporttype')),
            ],
            options={
                'verbose_name': 'Sport Type',
                'verbose_name_plural': 'Sport Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPhysioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('method', models.CharField(choices=[('formula', 'Basic (5 zones) - based on age(220 - age)'), ('karvonen', 'Fitness (5 zones) - Carvonen method (max HR minus rest HR)'), ('lthr', 'Professional (7 zones) - based on Lactate Threshold(Joe Friel)'), ('manual', 'Custom (3-7 zones) - user manually enters zones')], default='formula', max_length=15)),
                ('ai_adjustments_enabled', models.BooleanField(default=False, help_text='If True, allow AI offer recommendations to adjust zones based on workouts history and trends.')),
                ('zone_count_setting', models.PositiveSmallIntegerField(default=5, help_text='Target number of zones (3-7) to display in the UI, default = 5', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)])),
                ('max_hr', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)])),
                ('rest_hr', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(120)])),
                ('threshold_hr', models.PositiveSmallIntegerField(blank=True, help_text='Anaerobic threshold', null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(220)])),
                ('ftp_watts', models.PositiveSmallIntegerField(blank=True, help_text='Functional Threshold Power for cyclists', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(700)])),
                ('hr_zones', models.JSONField(default=dict, help_text='Heart rate zones based on the selected method')),
                ('power_zones', models.JSONField(blank=True, default=dict, help_text='Power zones for cyclists and bike workouts, same format as hr_zones but with wattage thresholds instead of HR')),
                ('lactate_testing_enabled', models.BooleanField(default=False, help_text='If True, show inline lactate input on workouts. Enable for pro/lab-tested athletes.')),
                ('sport_type', models.ForeignKey(blank=True, help_text='Sport-specific profile (null = general fallback used when no sport-specific exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.sporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('date', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Needed for checking duplicates by overlapping time windows', null=True)),
                ('duration', models.DurationField(help_text='Format: HH:MM:SS (e.g., 01:30:00)')),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('verification_level', models.CharField(choices=[('raw', 'Raw Sync'), ('verified', 'Verified by User'), ('expert', 'Expert')], default='raw', max_length=20)),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('calories', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20000)])),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='1 = very light, 10 = max effort', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('feeling', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Normal'), (4, 'Good'), (5, 'Great')], help_text="User's subjective mental/physical feeling about the workout (1-5, from terrible to great)", null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=10, null=True)),
                ('elevation_gain', models.PositiveSmallIntegerField(blank=True, help_text='Elevation gain in meters', null=True)),
                ('avg_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Average speed in km/h', max_digits=5, null=True)),
                ('avg_pace', models.PositiveIntegerField(blank=True, help_text='Average pace in seconds per kilometer', null=True)),
                ('avg_power', models.PositiveSmallIntegerField(blank=True, help_text='Average power in Watts', null=True, validators=[django.core.validators.MaxValueValidator(2000)])),
                ('avg_cadence', models.PositiveSmallIntegerField(blank=True, help_text='RPM (cycling) or SPM (running)', null=True, validators=[django.core.validators.MaxValueValidator(250)])),
                ('tss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('training_load', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated training load (TSS/TRIMP) for AI color indicators', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('training_load_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('hr_zones_data', models.JSONField(blank=True, default=dict, help_text='Time in HR zones (seconds)')),
                ('power_zones_data', models.JSONField(blank=True, default=dict, help_text='Time in Power zones (seconds)')),
                ('internal_stress_score', models.DecimalField(blank=True, decimal_places=2, help_text='Our own load calculation (Hybrid: HR + Power + RPE)', max_digits=6, null=True)),
                ('variability_index', models.DecimalField(blank=True, decimal_places=2, help_text="NP to Avg Power (how 'jerky' the training was)", max_digits=4, null=True)),
                ('additional_metrics', models.JSONField(blank=True, default=dict, help_text='Structured extras: pedal balance, outside temp, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='workouts.workout')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.datasource')),
                ('sport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.sporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_physio_profile', models.ForeignKey(blank=True, help_text='Physiological profile of the user at the time of workout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='workouts.userphysioprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LactateMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(help_text='Date and time when lactate was measured (YYYY-MM-DD HH:MM)')),
                ('hr_bpm', models.PositiveSmallIntegerField(blank=True, help_text='Heart rate in bpm at the time of measurement', null=True)),
                ('mmol', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(30.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactate_measurements', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lactate_measurements', to='workouts.workout')),
            ],
            options={
                'ordering': ['measured_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_api_version', models.CharField(blank=True, help_text="Provider's API version at sync time (header echo or doc version)", max_length=20)),
                ('schema_version', models.CharField(help_text='Our parser version used when ingesting this payload', max_length=20)),
                ('payload', models.JSONField(help_text='Sanitized provider response (sensitive keys redacted via sanitize_payload)')),
                ('provider_workout_id', models.CharField(blank=True, db_index=True, help_text='Copy of Workout.external_id for orphan identification', max_length=255)),
                ('workout_started_at', models.DateTimeField(blank=True, db_index=True, help_text='Copy of Workout.date for searching workout by timeline in bin', null=True)),
                ('payload_sha256', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_payloads', to=settings.AUTH_USER_MODEL)),
                ('workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_payload', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_snapshot', models.PositiveIntegerField(blank=True, help_text='Snapshot of user.id at write time. Survives user deletion (SET_NULL above).', null=True)),
                ('user_email_snapshot', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('token_refresh', 'Token Refreshed'), ('sync_success', 'Sync Success'), ('sync_failed', 'Sync Failed'), ('source_connect', 'Source Connected'), ('source_disconnect', 'Source Disconnected'), ('expert_edit', 'Expert Edit'), ('duplicate_resolved', 'Duplicate Resolved'), ('athlete_data_view', 'Athlete data viewed by coach'), ('account_deletion_scheduled', 'Account Deletion Scheduled(GDPR 30 days window)'), ('account_deletion_completed', 'Account Deletion Completed Permanently')], max_length=50)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='workouts_au_user_id_62642c_idx'), models.Index(fields=['user_id_snapshot', '-created_at'], name='workouts_au_user_id_237e21_idx'), models.Index(fields=['action', '-created_at'], name='workouts_au_action_082175_idx'), models.Index(fields=['ip_address', '-created_at'], name='workouts_au_ip_addr_5d762c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_user_id__isnull', False)), fields=('platform', 'provider_user_id'), name='unique_provider_user_id_per_platform'),
        ),
        migrations.AddIndex(
            model_name='healthmetrics',
            index=models.Index(fields=['user', 'is_primary', 'date'], name='workouts_he_user_id_b47d0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthmetrics',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'source'), name='unique_user_date_source_healthmetrics'),
        ),
        migrations.AddConstraint(
            model_name='healthmetrics',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('user', 'date'), name='unique_user_date_manual_entry'),
        ),
        migrations.AddConstraint(
            model_name='healthmetrics',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'date'), name='unique_primary_health_per_user_date'),
        ),
        migrations.AddIndex(
            model_name='userphysioprofile',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='workouts_us_user_id_8f3139_idx'),
        ),
        migrations.AddConstraint(
            model_name='userphysioprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'sport_type'), name='unique_active_physio_per_user_sport', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date', 'is_primary'], name='workouts_wo_user_id_f4f511_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_external_workout_per_source'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duplicate_of__isnull', True), ('is_primary', True)), models.Q(('duplicate_of__isnull', False), ('is_primary', False)), _connector='OR'), name='workout_primary_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='workoutrawpayload',
            index=models.Index(fields=['provider', 'received_at'], name='workouts_wo_provide_dce815_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutrawpayload',
            constraint=models.UniqueConstraint(fields=('user', 'payload_sha256'), name='unique_payload_hash_per_user'),
        ),
    ]
