# Generated by Django 6.0.4 on 2026-04-12 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('recovery', 'Recovery'), ('sport_specific', 'Sport Specific')], max_length=30)),
            ],
            options={
                'verbose_name': 'Sport Type',
                'verbose_name_plural': 'Sport Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('duration', models.DurationField(help_text='Format: HH:MM:SS (e.g., 01:30:00)')),
                ('notes', models.TextField(blank=True)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Rate of Perceived Exertion (1-10 scale), 1 = very light, 10 = max effort', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lactate', models.DecimalField(blank=True, decimal_places=2, help_text='Lactate concentration in mmol/L, e.g. 2.3, leave blank if not measured', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(30.0)])),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('training_load', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated training load (TRIMP). For professional insights, lactate data analyzed by AI agent', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.sporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='workouts_wo_user_id_f1c995_idx')],
            },
        ),
    ]
