# Generated by Django 6.0.4 on 2026-05-19 14:50

import django.core.validators
import django.db.models.deletion
import workouts.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('token_refresh', 'Token Refreshed'), ('sync_success', 'Sync Success'), ('sync_failed', 'Sync Failed'), ('source_connect', 'Source Connected'), ('source_disconnect', 'Source Disconnected'), ('expert_edit', 'Expert Edit'), ('duplicate_resolved', 'Duplicate Resolved')], max_length=50)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whoop', 'Whoop'), ('oura', 'Oura Ring'), ('polar', 'Polar'), ('garmin', 'Garmin'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('strava', 'Strava'), ('wahoo', 'Wahoo'), ('suunto', 'Suunto'), ('coros', 'Coros'), ('ultrahuman', 'Ultrahuman'), ('myfitnesspal', 'MyFitnessPal'), ('eight_sleep', 'Eight Sleep'), ('manual', 'Manual Entry')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', workouts.crypto.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', workouts.crypto.EncryptedTextField(blank=True, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('provider_user_id', models.CharField(blank=True, help_text='User ID in provider system(e.g. Garmin Connect ID, Polar Flow ID)', max_length=255, null=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Oath scopes granted for this User while connecting')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source_label', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('perceived_readiness', models.PositiveSmallIntegerField(blank=True, help_text='Athlete self rate in the morning (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_duration', models.DurationField(blank=True, help_text='Total sleep duration, format: HH:MM:SS (e.g., 07:30:00)', null=True)),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recovery_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rhr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deep_sleep', models.DurationField(blank=True, help_text='Duration of deep sleep, format: HH:MM:SS (e.g., 02:00:00)', null=True)),
                ('rem_sleep', models.DurationField(blank=True, help_text='Duration of REM sleep, format: HH:MM:SS (e.g., 01:30:00)', null=True)),
                ('light_sleep', models.DurationField(blank=True, help_text='Duration of light sleep, format: HH:MM:SS (e.g., 04:00:00)', null=True)),
                ('awake_time', models.DurationField(blank=True, help_text='Duration of awake time during sleep, format: HH:MM:SS (e.g., 00:30:00)', null=True)),
                ('sleep_consistency', models.PositiveSmallIntegerField(blank=True, help_text='Sleep consistency 1-100% (Whoop Consistency, Oura Regularity and etc.)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=1, help_text='Respiratory rate in breaths per minute', max_digits=4, null=True)),
                ('skin_temp_delta', models.DecimalField(blank=True, decimal_places=1, help_text='Skin temperature', max_digits=4, null=True)),
                ('spo2_avg', models.DecimalField(blank=True, decimal_places=1, help_text='Average Blood Oxygen (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(85.0), django.core.validators.MaxValueValidator(100.0)])),
                ('spo2_min', models.DecimalField(blank=True, decimal_places=1, help_text='Min SP02 at night', max_digits=4, null=True)),
                ('vo2max', models.DecimalField(blank=True, decimal_places=1, help_text='VO2max ml/kg/min — Garmin/Polar estimate', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LactateMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(help_text='Date and time when lactate was measured, format: YYYY-MM-DD HH:MM')),
                ('hr_bpm', models.PositiveSmallIntegerField(blank=True, help_text='Heart rate in beats per minute at the time of lactate measurement', null=True)),
                ('mmol', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(30.0)])),
            ],
            options={
                'ordering': ['measured_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPhysioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('method', models.CharField(choices=[('formula', 'Formula 220-age'), ('karvonen', 'Karvonen Method'), ('lthr', 'Joe Friel LTHR'), ('manual', 'Manual'), ('ai', 'AI Calibrated')], default='formula', max_length=15)),
                ('max_hr', models.PositiveSmallIntegerField()),
                ('rest_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('threshold_hr', models.PositiveSmallIntegerField(blank=True, help_text='Anaerobic threshold', null=True)),
                ('ftp_watts', models.PositiveSmallIntegerField(blank=True, help_text='Functional Threshold Power for cyclists', null=True)),
                ('hr_zones', models.JSONField(default=dict, help_text='Heart rate zones based on the selected method')),
                ('power_zones', models.JSONField(blank=True, default=dict, help_text='Power zones for cyclists and bike workouts')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workouts_wo_user_id_f1c995_idx',
        ),
        migrations.AddField(
            model_name='sporttype',
            name='external_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sporttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='workouts.sporttype'),
        ),
        migrations.AddField(
            model_name='workout',
            name='additional_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workout',
            name='avg_cadence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='avg_pace',
            field=models.DurationField(blank=True, help_text='Average pace per kilometer, format: MM:SS (e.g., 05:30)', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='avg_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average speed in km/h', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='elevation_gain',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Elevation gain in meters', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='need for checking duplicates by crossing time', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='feeling',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='hr_zones_data',
            field=models.JSONField(blank=True, default=dict, help_text='Time in HR zones (seconds)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='internal_stress_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Our own load calculation (Hybrid: HR + Power + RPE)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='power_zones_data',
            field=models.JSONField(blank=True, default=dict, help_text='Time in Power zones (seconds)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='raw_api_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workout',
            name='training_load_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='tss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='variability_index',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="NP to Avg Power (how 'jerky' the training was)", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='verification_level',
            field=models.CharField(choices=[('raw', 'Raw Sync'), ('verified', 'Verified by User'), ('expert', 'Expert')], default='raw', max_length=20),
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('recovery', 'Recovery'), ('specific', 'Sport Specific')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = very light, 10 = max effort', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_load',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated training load (TSS/TRIMP) for AI color indicators', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.datasource'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date', 'is_primary'], name='workouts_wo_user_id_f4f511_idx'),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.datasource'),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lactatemeasurement',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactate_measurements', to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='userphysioprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='lactate',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='workouts_au_user_id_62642c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='workouts_au_action_082175_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='workouts_au_ip_addr_5d762c_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_user_id__isnull', False)), fields=('platform', 'provider_user_id'), name='unique_provider_user_id_per_platform'),
        ),
        migrations.AddIndex(
            model_name='healthmetrics',
            index=models.Index(fields=['user', 'is_primary', 'date'], name='workouts_he_user_id_b47d0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthmetrics',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'source'), name='unique_user_date_source_healthmetrics'),
        ),
        migrations.AddConstraint(
            model_name='healthmetrics',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('user', 'date'), name='unique_user_date_manual_entry'),
        ),
        migrations.AddIndex(
            model_name='userphysioprofile',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='workouts_us_user_id_8f3139_idx'),
        ),
    ]
